pipeline {
    agent any
    stages {
        stage('Build the job') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test was done') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('depolyment') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
